sudo: true

language: cpp

cache: ccache

os:
  - osx

osx_image: xcode9.4

matrix:
  include:
    - os: osx

before_install:
  - export PYTHONPATH=${PYTHONPATH}:${PWD}/python

install:
  - brew install ccache
  - export PATH="/usr/local/opt/ccache/libexec:$PATH"
  - source ci/travis/install.sh

# We build with 2 concurrent jobs to match the number of cores present on MacOS virutal machines.
# nproc does not report the correct number of cores reliably in Travis, so using nproc is not
# recommended.
# https://docs.travis-ci.com/user/reference/overview/
script:
  - export MXNET_STORAGE_FALLBACK_LOG_VERBOSE=0
  - mv make/osx.mk config.mk
  - make -j 2
